### ISSUE TITLE
Requires flip-link linker tool?

### ISSUE THREAD

**Issue by DM777-ms** [felipebalbi/mimxrt685s-examples#1]
![image](https://github.com/user-attachments/assets/7a02d2b3-1d14-4a45-887c-cd5bc5c98d75)

**Comment by felipebalbi** [comment]
Hi @DM777-ms,

`flip-link` is a tool, not a library we can depend on. I have added a note on `README.md` letting users know that `flip-link` must be installed.

Thank you
